### PR TITLE
Update and rearrange installation instructions

### PR DESCRIPTION
**Pull request by link2xt**

### CODE REVIEW

**Comment by melmothx** [comment]
@link2xt I'm reading this again https://github.com/melmothx/amusewiki/pull/265 after looking at the way `init-all.sh` is called. I thought that `init-all.sh` should have been updated to wrap carton (this way the invocation would still work unmodified). Am I missing something?

**Comment by melmothx** [comment]
@link2xt I have some requests:

I've amended =init-all.sh= to call carton exec, so that part should be restored. Now with carton the installation is more speedy, so I believe it's around 40 minutes or so (instead of the 2 hours).

In the doc there are calls to perl scripts without carton, which I think should be fixed as well.

The idea is that shell scripts, being wrappers, shouldn't need to be called with carton (instead, they should do that if calling amw scripts), while it's needed if they called directly. Maybe this should be stated as well in the doc.

Thoughts?

**Comment by link2xt** [comment]
I have pushed commits with fixes.

We can also start perl scripts with `#!/usr/bin/env carton exec`, but that needs some more discussion in amusewiki repo issues.

**Comment by melmothx** [comment]
Thanks!

**Pull request merged**
